CREATE TABLE [dbo].[Department] (
    [DEPARTMENT_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [MANAGER_ID]           INT           CONSTRAINT [DF__DEPARTMEN__MANAG__1273C1CD] DEFAULT (NULL) NULL,
    [NAME]                 NVARCHAR (45) NOT NULL,
    [PARENT_DEPARTMENT_ID] INT           CONSTRAINT [DF__DEPARTMEN__PAREN__1367E606] DEFAULT (NULL) NULL,
    CONSTRAINT [PK__DEPARTME__63E613623DCDFBB4] PRIMARY KEY CLUSTERED ([DEPARTMENT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNQ_DEPARTMENT_NAME]
    ON [dbo].[Department]([NAME] ASC);

