CREATE TABLE [dbo].[Job_Title] (
    [JOB_TITLE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION]  NVARCHAR (45) NOT NULL,
    CONSTRAINT [PK__JOB_TITL__5F42B01C2E2B295F] PRIMARY KEY CLUSTERED ([JOB_TITLE_ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UNQ_JOB_DESCRIPTION]
    ON [dbo].[Job_Title]([DESCRIPTION] ASC);

